### ISSUE TITLE
Clarify the relation and interworking between TSC and Commonalities. 

### ISSUE THREAD

**Issue by FrimanJan** [camaraproject/Governance#109]
Today we have following descriptions 

**Project Structure and Roles** 

CAMARA commonalities shall be processed in a Working Group “Commonalities” and one or more Sub Projects. The Working Group “Commonalities” works under the supervision of the TSC. The scope of the Working Group is to create guidelines, best practices and concept documents relevant for all API families. The commonalities Sub Projects shall work e.g. on the development of a common meta model that shall be used as a reference across the rest of the Sub Projects.

**Project charter.** Responsibilities for TSC

Discussions, seeking consensus, and where necessary, voting on technical matters relating to the code base that affect multiple projects; and
receive and resolve escalations from Sub Projects on blocked topics or areas where Sub Projects or Working Groups are seeking input from the TSC, i.e. when the established decision process did not end up in a resolution for that topic at Sub Project or Working Group level. 

It would be beneficial if we could define the process for how the interworking shall work a bit more in detail. E.g. rules or best practice for what shall be pushed to TSC from commonalities.

**Comment by hdamker** [comment]
@FrimanJan What would be your expected outcome of this issue? 

The Project charter has also the paragraph:

> **Technical decisions**
> 
> Technical decisions that only affect a single Sub Project are made informally by the maintainers of this Sub Project, and [lazy consensus](https://couchdb.apache.org/bylaws.html#lazy) is assumed. If no consensus can be reached, the matter may be resolved by majority vote.
> 
> Technical decisions that span multiple parts of the CAMARA Project should be discussed and made in the Commonalities Working Group or other Working Groups established by TSC for cross-project technical issues. Decisions are usually made by [lazy consensus](https://couchdb.apache.org/bylaws.html#lazy). If no consensus can be reached, the matter may be resolved by majority vote by the TSC.

From that it is clear that Commonalities has to push decision to TSC when there is not consensus found within the Working Group. 

Beyond that there are topics where the working group can ask for support, as happened e.g. for the topic of Release Management, or want to make sure that the TSC is aware of an important discussion. I'm not sure if that can be formalized.

**Comment by FrimanJan** [comment]
Thanks for the answer.

I think the process how decisions are taken is clear, and yes it might be hard to formalize everything. 

I was thinking of adding some details on the process before going into decision phase, e.g.
-Can TSC put tasks on Commonalities to investigate a topic and prepare material for later decision in TSC?

**Comment by hdamker** [comment]
Closing the issues as discussed within TSC Nov 16th.
