### ISSUE TITLE
Clarity on who are allowed to create new issues in Commonalities and TSC

### ISSUE THREAD

**Issue by FrimanJan** [camaraproject/Governance#113]
As a follow up to the [Issue #109 ](https://github.com/camaraproject/Governance/issues/109) Clarify the relation and interworking between TSC and Commonalities following addition is suggested to the project charter for clarity on who are allowed to create new issues.

Commonalities:

CAMARA commonalities shall be processed in a Working Group “Commonalities” and one or more Sub Projects. The Working Group “Commonalities” works under the supervision of the TSC. The scope of the Working Group is to create guidelines, best practices and concept documents relevant for all API families. The commonalities Sub Projects shall work e.g. on the development of a common meta model that shall be used as a reference across the rest of the Sub Projects. **_It is open for members of any working group to raise issues in the Commonalities Working group for relevant topics on a need basis._**  

TSC:

Discussions, seeking consensus, and where necessary, voting on technical matters relating to the code base that affect multiple projects; and receive and resolve escalations from Sub Projects on blocked topics or areas where Sub Projects or Working Groups are seeking input from the TSC, i.e. when the established decision process did not end up in a resolution for that topic at Sub Project or Working Group level. **_It is open for members of any working group to raise issues in the TSC group for relevant topics on a need basis._**

**Comment by hdamker** [comment]
@FrimanJan I've added the proposed sentences, slightly adapted to "It is open for members of any Sub Project or Working Group to raise issues in the TSC group for relevant topics on a need basis.", as this was the intention (not limiting it to Working Groups).
