### ISSUE TITLE
Camaraproject.org Scope Page - distinguish between End Consumers and Developers

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/Governance#123]
With issue camaraproject/WorkingGroups#207 , Markus had clarified the Scope page quite a bit, thanks @MarkusKuemmerle 

One more request:
We need to distinguish clearly between 'End Consumers' and Developers. IMO..
- Developers build application using the Service* API
- End Consumers use the applications that are built by the developers

If you agree, recommend changing API Consumption section to reflect that Developers are in the top orange box interacting with the portals. @MarkusKuemmerle, @hdamker , perhaps there is a variant of the NaaS Arch diagram that can be adopted here, what you have seen before from me?
Also, recommend clarifying this somewhere (nomenclature on top/bottom?).

cc: @gmuratk

**Comment by murthygorty** [comment]
Just to clarify my understanding, @MarkusKuemmerle , are you suggesting that we will call out that End Consumers here are API consumers? sounds great to me.

**Comment by MarkusKuemmerle** [comment]
@murthygorty: See https://github.com/camaraproject/Governance/pull/156

**Comment by murthygorty** [comment]
looks good @MarkusKuemmerle , thanks!
