### ISSUE TITLE
Questions / minor points

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/Governance#48]
Questions / minor points from Bart:
1.	In the repositories there is traceability for github documents, except for non-native formats such as PPT, Word, PDF or similar. These can only be updated as a whole. We need to think about a mechanism for this or avoid these.
2.	Changes in Project participantship section mentions that “Changes in Project participantship have to be announced on the CAMARA Project mailing list” but it does not state who should do this
3.	There are Sub Projects and Working groups, but it is not clear to me what is the difference.
4.	The FAQ, first question “How do I propose a decision” states that if no objection within a reasonable time, consider the decision made. But what is a reasonable amount of time?

**Comment by MarkusKuemmerle** [comment]
1. That's a feature of GitHub. We should use Markdown oder ADocs files instead.
2. The new Project participant should announce himself. I would add this to the section.
3. API (families) are developed in Sub Projects. Overarching topics which affect several API (families) are discussed and decided in Working groups. Please see description at the top of **Project Structure and Roles**
4. Fair point. I would add **"1 week"** to make it concrete

**Comment by Bart-Ericsson** [comment]
Good proposals, thanks
On the 1 week for reasonable time, how do we handle holiday periods? Since I expect limited meetings during those periods, perhaps we can say "1 week after most recent meeting"

**Comment by MarkusKuemmerle** [comment]
Fine for me, I would add "1 week after most recent meeting / email announcement of the decision"

**Comment by MarkusKuemmerle** [comment]
2. and 4. added to ProjectStructureAndRoles.md
