### ISSUE TITLE
Proposal for a New API for E.212/E.164 Mapping

### ISSUE THREAD

**Issue by ajamous** [camaraproject/Governance#74]
Hello Team,  

I’m writing to propose a new API for E.212/E.164 mapping  (MCCMNC <->Dial Code) to create accurate and up-to-date mapping list available to the public.  I believe that adopting this API under the CAMARA project has the potential to provide a single point of truth for E.212/E.164 mapping which doesn’t seem to exist anywhere at this time. This would enable anyone to find the most recent and accurate dial codes belonging to MCCMNC and vice versa globally, providing valuable information to users worldwide.  

Our team has spent considerable time and resources to create this API, and we believe it could benefit the wider community greatly. We would be honored to contribute this new API/Data to the CAMARA project and work with your team to make it available to developers worldwide.  

Please let me know if you are interested in learning more about this topic and how we can work together to make it available to wider community. I am happy to provide more details or answer any questions you may have.  

Thank you for your time and consideration. I look forward to hearing back from you soon.

**Comment by patrice-conil** [comment]
Hello @ajamous,
This is a nice idea.

**Comment by MarkusKuemmerle** [comment]
Moved to API Backlog Working Group: https://github.com/camaraproject/WorkingGroups/issues/192
