### ISSUE TITLE
Camaraproject.org Scope and Distribution Options driven through github also?

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/Governance#78]
Hi,
I noticed the main page on camaraproject.org has the same content as the 'Marketing' portion of github.

Would it make sense to have the same approach towards other sections of camaraproject.org as well? Selfish motive: I'd like to comment and influence the diagrams and content under '[Scope](https://camaraproject.org/scope/)' and '[Distribution Options](https://camaraproject.org/distribution-options/)' of camaraproject.org.

I'm hoping to leverage the same "github -> raise an issue" to request change :-) 
For now, I will raise new issues under 'Governance' with the inputs I currently have, hope that is ok.

cc: @gmuratk

**Comment by MarkusKuemmerle** [comment]
Hi @murthygorty,
you're invited to join the Marketing Working Group, that's the place where we discuss such topics, esp. the new scope description. And you're completely right, we use text blocks which are the same for GitHub, Website and marketing materials. That's already in place :-)

**Comment by murthygorty** [comment]
That's great to know - thanks for confirming that it is indeed the plan @MarkusKuemmerle! 

However, I'm unable to find "Scope" and 'Distribution Options' in the github @https://github.com/camaraproject/WorkingGroups/tree/main/Marketing/documentation/MarketingMaterial.
