### ISSUE TITLE
Camaraproject.org Distribution Options

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/Governance#79]
Hi,
'Distribution Options' part of Camaraproject.org looks very valuable. Request these considerations below:
1) Clarify who customer is --> I assume a 'Developer', not necessarily 'customer of the operator'.
2) We have been seeing needs where CustomerDeveloper uses another 'Dev Platform' with their own value-adds, which in turns uses operator API -- this may not necessarily be aggregator, just to be clear

**Comment by hdamker** [comment]
@MarkusKuemmerle this issue seems to be stale. Is this in scope of Marketing/"Outreach Committee"?

**Comment by murthygorty** [comment]
Hi @hdamker , @MarkusKuemmerle , just fyi, took a fresh look at the page and my commments are still relevant :-)
happy holidays and merry xmas.

**Comment by MarkusKuemmerle** [comment]
@murthygorty: I've changed the website, would you recheck?
https://camaraproject.org/distribution-options/

**Comment by murthygorty** [comment]
Thank you! Looks great and one small request @MarkusKuemmerle:  (not a showstopper)
- Consistent with [Scope page](https://camaraproject.org/scope/) rename the boxes from "SEP Operator 1" to "Telco 1 SEP"
- Add a second sentence under the color legend sentence that expands SEP to 'Service Exposure Platform'.

**Comment by MarkusKuemmerle** [comment]
Included last changes of @murthygorty

**Comment by murthygorty** [comment]
thank you so much!
