### ISSUE TITLE
Handling of private repos

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/Governance#83]
- How continue with ASL?
- Private repos for sensitive APIs?

**Comment by hdamker** [comment]
As of [TSC-2023-10-19-Meeting-Minutes.md](https://github.com/camaraproject/Governance/blob/main/documentation/MeetingMinutes/TSC/TSC-2023-10-19-Meeting-Minutes.md):

- Decision was taken within TSC on Sept 21st that there will be no private repositories in CAMARA hosted
- Eric proposed to archive the exisitng private repository Anonymised Subscriber Identifier. Functionality to be reconsidered if there is a request from OGW product team.
- The proposal was accepted.

**Comment by hdamker** [comment]
https://github.com/camaraproject/AnonymisedSubscriberIdentifier is now archived and this issue done. 
If there is a need for later access please contact CAMARA admins.
