### ISSUE TITLE
Update Project charter doc to amend the voting principles content

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/Governance#96]
The current voting principles in project charter doc states - 

> Technical decisions that span multiple parts of the CAMARA Project should be discussed and made in the Commonalities Working Group. Decisions are usually made by [lazy consensus](https://couchdb.apache.org/bylaws.html#lazy). If no consensus can be reached, the matter may be resolved by majority vote by the TSC, Sub Project or Working Group.

> 

I would like to propose to the TSC that for commonalities and id-consent, if these working groups are not able to come to a consensus on a particular topic, the voting should be undertaken in the TSC as the decisions taken in these 2 working groups impacts all/most subprojects.

**Comment by chrishowell** [comment]
I think I'd go even further than that though, as Commonalities and Identity and Consent sub-groups have wide-reaching implications.
I'd prefer that anything that got approved in those groups had to come to the TSC for a vote (and generally get waved through)...

**Comment by Bart-Ericsson** [comment]
I think it's important that we address this, but I assume we need to address it in Camara governance since it needs a change in the overall governance rules. @MarkusKuemmerle can we ensure this is on the agenda for the next governance meeting?

**Comment by MarkusKuemmerle** [comment]
@Bart-Ericsson : A change of the technical charter is in responsibility of the TSC. Governing board is working on financials and outreach / marketing. @hdamker : Would you add this to the agenda of one of the next TSC meetings?

**Comment by MarkusKuemmerle** [comment]
@Bart-Ericsson : A change of the technical charter is in responsibility of the TSC. Governing board is working on financials and outreach / marketing. @hdamker : Would you add this to the agenda of one of the next TSC meetings?

**Comment by ShutingQing** [comment]
> The current voting principles in project charter doc states -
> 
> > Technical decisions that span multiple parts of the CAMARA Project should be discussed and made in the Commonalities Working Group. Decisions are usually made by [lazy consensus](https://couchdb.apache.org/bylaws.html#lazy). If no consensus can be reached, the matter may be resolved by majority vote by the TSC, Sub Project or Working Group.
> 
> > 
> 
> I would like to propose to the TSC that for commonalities and id-consent, if these working groups are not able to come to a consensus on a particular topic, the voting should be undertaken in the TSC as the decisions taken in these 2 working groups impacts all/most subprojects.

That's a good suggestion. Based on shilpa's suggestion, I would also suggest we need to align the way of vote. Reason for each vote is required, either for why support or why not support. This is suggested to be based on technical perspective.

**Comment by hdamker** [comment]
From [TSC-2023-10-19-Meeting-Minutes.md](https://github.com/camaraproject/Governance/blob/main/documentation/MeetingMinutes/TSC/TSC-2023-10-19-Meeting-Minutes.md)

> Voting in Commonalities and ICM groups: as their decisions affect many other working groups, discussions needing a voting should be escalated to TSC.

I will prepare a PR on the Project Charter for that.

**Comment by hdamker** [comment]
@ShutingQing 

> Based on shilpa's suggestion, I would also suggest we need to align the way of vote. Reason for each vote is required, either for why support or why not support. This is suggested to be based on technical perspective.

Voting principles are already described within the [ProjectCharter.md](https://github.com/camaraproject/Governance/blob/main/ProjectCharter.md). The proposal the participants are voting on have to be clearly defined and should reference any discussion leading up to this point. But there is no requirement to add a reason to a casted vote. The TSC is also not only deciding based on technical perspective, see the [responsibilities of the TSC](https://github.com/camaraproject/Governance/blob/main/ProjectCharter.md#:~:text=Responsibilities%3A%20The%20TSC%20is%20responsible).
