### ISSUE TITLE
Housekeeping: Bring repo templates changes to all other repos

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/Governance#98]
Currently we have to changes in our lead repo template:

- https://github.com/camaraproject/Template_Lead_Repository/tree/main/.github
- https://github.com/camaraproject/Template_Lead_Repository/pull/1

Shall these also be included in all other lead repos?

**Comment by hdamker** [comment]
> * https://github.com/camaraproject/Template_Lead_Repository/tree/main/.github

The templates are already in most lead repositories. Would be good to add them also to:
* ClickToDial
* EdgeCloud
* KnowYourCustomer

Note: §repo_name§ need to be replaced in config.yml when copying from the template and discussions need to be enabled within the repo

> * [Added Test_definitions folder under code Template_Lead_Repository#1](https://github.com/camaraproject/Template_Lead_Repository/pull/1)

I don't have a clear opinion here, but it makes sense. README.md in the new directory should have clear description about purpose of the folder

**Comment by hdamker** [comment]
We will create PRs for the three sub projects which have not yet the Git template
- ClickToDial
- EdgeCloud
- KnowYourCustomer
to achieve uniformity across the sub projects.

**Comment by hdamker** [comment]
Closing the issue as the necessary PRs are created.

**Comment by hdamker** [comment]
Closing the issue as the necessary PRs within sub projects are created.
